language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
env:
  matrix:
    - PLONE_VERSION=4.2
    # Nos demais pacotes plonegovbr, como não testo as versões além do Plone
    # 4.3 (ou seja, por padrão testo só a 4.3), não uso a variável
    # PLONE_VERSION, apenas a MASTER e a PENDING_RELEASE.
    - PLONE_VERSION=4.3 MASTER=true
    - PLONE_VERSION=4.3 PENDING_RELEASE=true
    - PLONE_VERSION=5.0
matrix:
  allow_failures:
    - env: PLONE_VERSION=4.2
    - env: PLONE_VERSION=4.3 MASTER=true
    - env: PLONE_VERSION=5.0
  fast_finish: true
install:
  # Remova a linha que aponta para o versions do novo release, por padrão 4.3,
  # se o job for o 4.2, 5.0  ou o que tem que pegar do master.
  - test "$MASTER" -o "$PLONE_VERSION" = 4.2 -o "$PLONE_VERSION" = 5.0 && sed -ie '/https:\/\/raw\.githubusercontent\.com\/plonegovbr\/portal\.buildout\/master\/buildout\.d\/versions\.cfg/d' buildout.cfg || true
  - sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
  - bin/buildout annotate
  - bin/buildout
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  # barra, no momento, não possui testes do tipo "Robots", ao contrário dos
  # demais pacotes em plonegovbr.
  - bin/createcoverage -t "--layer=!Robot"
  - pip install coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plonegovbr
